#### Aliases
aliases = []

#### Dependencies
dependencies = [
	"URL"
]

#### Specification Link
spec = "https://url.spec.whatwg.org/#dom-url-tojson"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/API/URL/toJSON"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "<71"
bb = "*"
chrome = "<71"
edge = "<17"
edge_mob = "<17"
firefox = "<54"
ios_chr = "<11"
ios_saf = "<11"
ie = "9 - *"
ie_mob = "9 - *"
opera = "<58"
op_mini = "<50"
safari = "<11"
firefox_mob = "<54"
samsung_mob = "<10"
